name    'ghoneycutt-redhat'
version '0.1.1'
source 'git@github.com:ghoneycutt/puppet-module-redhat.git'
author 'ghoneycutt'
license 'Apache License, Version 2.0'
summary 'Manage RedHat systems'
description 'Manage RedHat (or where osfamily is redhat) specific bits'
project_page 'https://github.com/ghoneycutt/puppet-module-redhat'

dependency 'puppetlabs/stdlib', '3.2.x'
